#!/bin/bash

PGNAME="dummy"
PATTERN=
TASKDIR=
DESKNAME=
ENVNAME=
TASKNAME=
PREFIX="${TASKDIR}"

die() {
	echo "$@" >&2
	exit 1
}

function usage()
{
    cat << EOF
Usage: tec dummy [OPTION]... [ID]...
    Find items in database.

    Options:
      -d DESK   desk name
      -e ENV    environment name

    Arguments:
      ID        task ID
EOF
}


OPTS=$(getopt -o d:e:i:P:T:h --long desk:,env:,taskid:,pgndir:,taskdir:help -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -d)
            DESKNAME="$2"
            shift 2
            ;;
        -e)
            ENVNAME="$2"
            shift 2
            ;;
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -P)
            PGNDIR="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        -h)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "$PGNAME: invalid option '$1'" >&2
            exit 1
    esac
done
CMD="$1"


function dummy_add()
{
    return 0;
}

function dummy_cat()
{
    echo "key: dummy value"
}

function dummy_cd()
{
    return 0;
}

function dummy_ls()
{
    return 0;
}

function dummy_mv()
{
    return 0;
}

function dummy_rm()
{
    return 0;
}

function dummy_set()
{
    return 0;
}


if [ "$CMD" = "add" ]; then
    dummy_add "$@"
elif [ "$CMD" = "cat" ]; then
    dummy_cat "$@"
elif [ -z "$CMD" ]; then
    die "'$PGNAME': command is not passed"
else
    die "'$PGNAME': '$CMD' no such command"
fi
